version: '3.9'

services:

  eurekaserver:
    build: ./eurekaserver
    container_name: eurekaserver
    healthcheck:
      test: "curl --fail --silent localhost:8761/actuator/health | grep UP || exit 1"
      interval: 10s
    networks:
      - springcloud

  configserve:
    build: ./configserve
    container_name: configserve
    healthcheck:
      test: "curl --fail --silent localhost:9999/actuator/health | grep UP || exit 1"
      interval: 10s
    networks:
      - springcloud

  domaine-ms:
    build: ./domaine-microservice
    container_name: domaine-ms
    environment:
      - DISCOVERY_SERVICE_URL=http://eurekaserver:8761/eureka/
      - CONFIG_SERVICE_URL=http://configserve:9999
      - SPRING_PROFILES_ACTIVE=default
    healthcheck:
      test: "curl --fail --silent localhost:8083/actuator/health | grep UP || exit 1"
    depends_on:
      eurekaserver:
        condition: service_healthy
      configserve:
        condition: service_healthy
    networks:
      - springcloud

  domain-ms2:
    build: ./domaine-microservice
    container_name: domaine-ms2
    environment:
      - DISCOVERY_SERVICE_URL=http://eurekaserver:8761/eureka/
      - CONFIG_SERVICE_URL=http://configserve:9999
    healthcheck:
      test: "curl --fail --silent localhost:8083/actuator/health | grep UP || exit 1"
    depends_on:
      eurekaserver:
        condition: service_healthy
      configserve:
        condition: service_healthy
    networks:
      - springcloud

  universite-ms:
    build: ./universite-microservice
    container_name: universite-ms
    environment:
      - DISCOVERY_SERVICE_URL=http://eurekaserver:8761/eureka/
      - CONFIG_SERVICE_URL=http://configserve:9999
    depends_on:
      eurekaserver:
        condition: service_healthy
      configserve:
        condition: service_healthy
      domaine-ms:
        condition: service_healthy
    networks:
      - springcloud

  gatewayserver:
    build: ./gatewayserver
    container_name: gatewayserver
    ports:
      - "8888:8888"
    environment:
      - DISCOVERY_SERVICE_URL=http://eurekaserver:8761/eureka/
      - CONFIG_SERVICE_URL=http://configserve:9999
    depends_on:
      eurekaserver:
        condition: service_healthy
      configserve:
        condition: service_healthy
    networks:
      - springcloud

networks:
  springcloud:
    driver: bridge
